[package]
name = "lasy"
version = "0.3.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A small library dedicated to LASER path optimisation."
edition = "2018"

[dependencies]
petgraph = { version = "0.5", default-features = false }
